ocean_dev/contact_app/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views


router = DefaultRouter()
router.register(r'lead', views.LeadsViewSet)
router.register(r'contact', views.ContactAddViewSet)

urlpatterns = [
    path('', include(router.urls))
]

ocean_dev/ocean_dev/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from rest_framework.permissions import AllowAny
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Ocean Dev API",
        default_version='v1',
        description="Ocean Dev API details"
    ),
    public=True,
    permission_classes=(AllowAny,),
)

urlpatterns = [
    path('doc/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('admin/', admin.site.urls),
    path('contacts/', include('contact_app.urls'))

]

ocean_dev/contact_app/models.py
from django.db import models
from django.db.models.signals import post_save
from django.conf import settings
from utils.utility import lead_send_email, contact_send_email


class LeadsModel(models.Model):
    """
    Model class for Leads Table(smv/supplier contact info)
    """

    first_name = models.CharField(max_length=100, blank=True)
    last_name = models.CharField(max_length=100, blank=True)
    company_name = models.CharField(max_length=200, blank=True)
    company_email = models.EmailField(max_length=200, blank=False)
    company_website = models.URLField(max_length=200, blank=True)
    phone_number = models.CharField(max_length=50, blank=True)
    company_registered_in = models.CharField(max_length=100, blank=True)
    annual_revenue = models.CharField(max_length=100, blank=True, default=None)
    description = models.TextField(blank=True)
    role = models.PositiveSmallIntegerField(choices=settings.ROLE_CHOICES, blank=True, null=True, default=1)

    def __str__(self):
        return self.company_email


class ContactModel(models.Model):
    """
    Model class for Contact Table (Contact form)
    """
    name = models.CharField(max_length=100, blank=True)
    mobile = models.CharField(max_length=50, blank=True)
    email_address = models.EmailField(max_length=200, blank=False)
    message = models.TextField(blank=True)

    def __str__(self):
        return self.email_address


def leads_send_admin_email(instance, **kwargs):
    """
    Initiating sending mails when LeadsModel is created
    """
    lead_send_email(subject="Leads Data", model_instance=instance, recipient_email=settings.ADMIN_EMAIL)


def contact_send_admin_email(instance, **kwargs):
    """
    Initiating sending mails when ContactModel is created
    """
    contact_send_email(subject="Contact Info Data", model_instance=instance, recipient_email=settings.ADMIN_EMAIL)


post_save.connect(leads_send_admin_email, sender=LeadsModel)

post_save.connect(contact_send_admin_email, sender=ContactModel)

ocean_dev/contact_app/views.py
from rest_framework.viewsets import ModelViewSet
from .permissions import IsAdminOrCreateOnly
from .models import LeadsModel, ContactModel
from .serializers import LeadsModelSerializers, ContactModelSerializers


class LeadsViewSet(ModelViewSet):
    """
    Class for CRUD operations in LeadsModel
    """
    permission_classes = [IsAdminOrCreateOnly]
    queryset = LeadsModel.objects.all()
    serializer_class = LeadsModelSerializers


class ContactAddViewSet(ModelViewSet):
    """
    Class for CRUD operations in the ContactModel
    """
    permission_classes = [IsAdminOrCreateOnly]
    queryset = ContactModel.objects.all()
    serializer_class = ContactModelSerializers

ocean_dev/templates/contacts_app/contact_info.html
Hi,

<h4>Contacts Info(Contact Form)</h4>

{% if contact_data.name %}
  <h5>Name: {{ contact_data.name }}</h5>
{% endif %}
{% if contact_data.mobile %}
  <h5>Mobile: {{ contact_data.mobile }}</h5>
{% endif %}
{% if contact_data.email_address %}
  <h5>Email Address: {{ contact_data.email_address }}</h5>
{% endif %}
{% if contact_data.message %}
  <h5>Company Email: {{ contact_data.message }}</h5>
{% endif %}

<h5>
  Regards
</h5>

ocean_dev/templates/contacts_app/leads_info.html
Hi,

<h4>Leads Info(Apply for growth capital)</h4>

{% if leads_data.first_name %}
  <h5>First Name: {{ leads_data.first_name }}</h5>
{% endif %}
{% if leads_data.last_name %}
  <h5>Last Name: {{ leads_data.last_name }}</h5>
{% endif %}
{% if leads_data.company_name %}
  <h5>Company Name: {{ leads_data.company_name }}</h5>
{% endif %}
{% if leads_data.company_email %}
  <h5>Company Email: {{ leads_data.company_email }}</h5>
{% endif %}
{% if leads_data.company_website %}
  <h5>Company Website: {{ leads_data.company_website }}</h5>
{% endif %}
{% if leads_data.phone_number %}
  <h5>Phone Number: {{ leads_data.phone_number }}</h5>
{% endif %}
{% if leads_data.annual_revenue %}
  <h5>Annual Revenue: {{ leads_data.get_annual_revenue_display }}</h5>
{% endif %}
{% if leads_data.description %}
  <h5>Description: {{ leads_data.description }}</h5>
{% endif %}
{% if leads_data.company_role %}
  <h5>Description: {{ leads_data.get_company_role_display }}</h5>
{% endif %}

<h5>
  Regards
</h5>